<a href="https://colab.research.google.com/github/Waleedprw22/Work_Public/blob/main/Breast_Cancer_NN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from typing import Tuple

import numpy as np
import pandas as pd

from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
data = pd.read_csv("https://raw.githubusercontent.com/changyaochen/MECE4520/master/data/breast_cancer.csv")
data["label"] = data["diagnosis"].apply(lambda x: 0 if x == "B" else 1)
data.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave_mean  ...  \
0          0.11840           0.27760          0.3001       0.14710  ...   
1          0.08474           0.07864          0.0869       0.07017  ...   
2          0.10960           0.15990          0.1974       0.12790  ...   
3          0.14250           0.28390          0.2414       0.10520  ...   
4          0.10030           0.13280          0.1980       0.10430  ...   

   texture_extreme  perimeter_extreme  area_extreme  smoothness_extreme  \
0            17.33             184.60        2019.0              0.1622   
1            23.41             158.80        1956.0              0.1238   
2            25.53             152.50        1709.0              0.1444   
3            26.50              98.87         567.7              0.2098   
4            16.67             152.20        1575.0              0.1374   

   compactness_extreme  concavity_extreme  concave_extreme  symmetry_extreme  \
0               0.6656             0.7119           0.2654            0.4601   
1               0.1866             0.2416           0.1860            0.2750   
2               0.4245             0.4504           0.2430            0.3613   
3               0.8663             0.6869           0.2575            0.6638   
4               0.2050             0.4000           0.1625            0.2364   

   fractal_extreme  label  
0          0.11890      1  
1          0.08902      1  
2          0.08758      1  
3          0.17300      1  
4          0.07678      1  

[5 rows x 33 columns]

In [ ]:
features = [
    "radius_extreme",
    "texture_extreme",
    "perimeter_extreme",
]
label = "label"

# train test split
X_raw, X_raw_test, Y, Y_test = train_test_split(data[features].values, data[label].values, test_size=0.2, random_state=42)

# Standardize the input
scaler = StandardScaler()
scaler.fit(X_raw)
X = scaler.transform(X_raw)
X_test = scaler.transform(X_raw_test)
print(X.shape)
# formatting
Y = Y.reshape((-1, 1))


(455, 3)


In [ ]:
# forward pass for a simple 2-layer NN, with 3 hidden units
np.random.seed(10)

def sigmoid(x):
    """Calculates sigmoid function."""
    return 1. / (1 + np.exp(-x))

# parameters for the first layer
W_1 = np.ones((5, X.shape[1])) * 0.1
print(f"Shape of W_1 is {W_1.shape}")


b_1 = np.ones((5,1))
print(f"Shape of b_1 is {b_1.shape}")

# parameters for the second layer
W_2 = np.ones((1, 1))
print(f"Shape of W_2 is {W_2.shape}")


b_2 = np.ones((1, 1)) * 0.1
print(f"Shape of b_1 is {b_2.shape}")

# calculate the forward propagation
Z_1 = X @ W_1.T
print(f"\nShape of Z_1 is {Z_1.shape}")
print("Samples for Z_1:")
print(Z_1[:5])




Shape of W_1 is (5, 3)
Shape of b_1 is (5, 1)
Shape of W_2 is (1, 1)
Shape of b_1 is (1, 1)

Shape of Z_1 is (455, 5)
Samples for Z_1:
[[-0.29570909 -0.29570909 -0.29570909 -0.29570909 -0.29570909]
 [ 0.55662103  0.55662103  0.55662103  0.55662103  0.55662103]
 [-0.35813153 -0.35813153 -0.35813153 -0.35813153 -0.35813153]
 [-0.01092391 -0.01092391 -0.01092391 -0.01092391 -0.01092391]
 [-0.35368832 -0.35368832 -0.35368832 -0.35368832 -0.35368832]]


In [ ]:
# train a NN with Keras
from tensorflow import keras
from tensorflow.keras import layers
import pandas as pd


In [ ]:


model = keras.Sequential([
        layers.Dense(units=5, activation = 'relu', input_shape = [X.shape[1]]),
        layers.Dense(units=1, activation='sigmoid'),
])

model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
)

In [ ]:
history = model.fit(
    X, Y,
    validation_data=(X_test, Y_test),
    batch_size=32,
    epochs=20,
    verbose=1,
    shuffle=True,
)

Epoch 1/20
15/15 [==============================] - 2s 35ms/step - loss: 0.6701 - val_loss: 0.6098
Epoch 2/20
15/15 [==============================] - 0s 6ms/step - loss: 0.6328 - val_loss: 0.5757
Epoch 3/20
15/15 [==============================] - 0s 5ms/step - loss: 0.5999 - val_loss: 0.5447
Epoch 4/20
15/15 [==============================] - 0s 6ms/step - loss: 0.5699 - val_loss: 0.5164
Epoch 5/20
15/15 [==============================] - 0s 6ms/step - loss: 0.5424 - val_loss: 0.4905
Epoch 6/20
15/15 [==============================] - 0s 6ms/step - loss: 0.5177 - val_loss: 0.4678
Epoch 7/20
15/15 [==============================] - 0s 5ms/step - loss: 0.4947 - val_loss: 0.4469
Epoch 8/20
15/15 [==============================] - 0s 5ms/step - loss: 0.4739 - val_loss: 0.4265
Epoch 9/20
15/15 [==============================] - 0s 5ms/step - loss: 0.4535 - val_loss: 0.4083
Epoch 10/20
15/15 [==============================] - 0s 5ms/step - loss: 0.4353 - val_loss: 0.3917
Epoch 11/20
15/15 

In [ ]:
roc_auc_score(y_true=Y_test, y_score=model.predict(X_test))

4/4 [==============================] - 0s 7ms/step


0.9921388797903702

In [ ]:

error = history.history['loss']
print(f"The value of the logloss metric is {error[len(error) - 1]}")



The value of the logloss metric is 0.3110402226448059
